# .github/workflows/main.yaml
name: Main

on: [push]
jobs:
  vm-job:
  steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Run tests
      run: |
      bundle exec rspec
